// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwbbyozjoxpwnigyahme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3YmJ5b3pqb3hwd25pZ3lhaG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNjcyNDEsImV4cCI6MjA3NTc0MzI0MX0.7DRWjFf-M23dJEXbSSs9m2DLLbUB7xFAysv_3kvUMHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});